import localFont from "next/font/local";
import "./globals.css";
import Navbar from "./Component/Navbar";
import Footer from "./Component/Footer";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "News Portal",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
  
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`} 
      >
        <div className="max-w-screen-xl mx-auto">
        <Navbar></Navbar>
        <div>{children}</div>
        <div><Footer></Footer> </div>
        </div>

     
      </body>
  
    </html>
  );
}
